### PR TITLE
Removed the green bar at the bottom of the screen on Chrome

### LINKED ISSUE #276: Figure out what is up with the greenspace at the bottom of the arbo page
I know this is related to the filters component and something to do with how we are handling overflow (not correctly) but have not been able to figure out why yet

### PR DESCRIPTION
**Pull request by SeanKennyNF**
Resolves #276.

Firefox:
Peek 2024-04-13 20-55

Chrome:
Peek 2024-04-13 20-56

### CODE REVIEW

**Comment by HimanshuRanka** [comment]
I tried this as well, but it breaks header navigation...

**Review by HimanshuRanka — CHANGES_REQUESTED** [review]
If we use header navigation it blocks the header and we can no longer scroll up to it, we need something more involeved.

This is definitely related to filters (removing the filter component fixes the issue) not sure why though

**Comment by SeanKennyNF** [comment]
> If we use header navigation it blocks the header and we can no longer scroll up to it, we need something more involeved.
>
> This is definitely related to filters (removing the filter component fixes the issue) not sure why though

Yeah I'm actually trying to hit both this one and the header one together. Yeah you're right these are kind of related.

**Comment by SeanKennyNF** [comment]
Actually yeah let's close this guy. I'm opening something a bit more comprehensive :+1:

**Pull request closed without merging**
